version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: docker-test
    container_name: docker-test_c
    ports:
      - 8080:3000
    volumes:
      - ./:/app
