#syntax=docker/dockerfile:1
FROM node:18-buster as build

WORKDIR /app
COPY package.json .
RUN yarn install
COPY . .

RUN yarn build

FROM nginx:alpine-perl as prod

COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]